{
  "comments": [
    {
      "key": {
        "uuid": "1af78d9a_ebf091cb",
        "filename": "dci/grafana/engine.py",
        "patchSetId": 8
      },
      "lineNbr": 28,
      "author": {
        "id": 30
      },
      "writtenOn": "2016-04-11T19:53:34Z",
      "side": 1,
      "message": "if GRAFANA_HOST is None, we should just disable Grafana support.",
      "revId": "0b7b4dba6fbd3733983fa22988de192e83432cee",
      "serverId": "6c1dc8ef-8b94-40e4-bd83-c2359d45ecc0",
      "unresolved": false
    }
  ]
}